#!/usr/bin/Rscript

# Script to assess reassortment from posterior samples of trees using multidimensional scaling.
# Author: Mathieu Fourment
#
# Plot an MDS of 1 or more genes
#
# colOfInterest can be the tMRCA of predefined clades
# The input files are the log files generated by BEAST. Alternatively a csv file can be used
# with all the data appened after one another. The counts variable is important for more than one
# matrix in order to correctly label the membership of a cloud of points to a gene.


# using log files from BEAST
files <- c("file1.log","file2.log","file3.log")
burnins <- c(9500,9500,9500)
colOfInterest <- 5:29

matCount <- process.beast.files(files, burnins, colOfInterest)
mat <- matCount[["data"]
counts <- matCount[["counts"]]


# or using a file containing all the data combined
# Can be used with patristic distances (See: Bahl et al, submitted)
files <- c("file1.log")
mat <- as.matrix(read.csv(files[1], head=FALSE, sep="," ))
counts <- rep(500, 3)



corrMat <- 1-cor(t(mat))
mds <- cmdscale(corrMat)

# PLOTTING

# trasparency
colors <- c("#228b2222", "#ff000022", "#0000cd22")
# less transparent
colors <- c("#228b2299", "#ff000099", "#0000cd99")
#opaque (for the legend)
legends <- c("#228b22", "#ff0000", "#0000cd")


###########################
# 2D PLOT

minx <- min(mds[,1])
maxx <- max(mds[,1])
miny <- min(mds[,2])
maxy <- max(mds[,2])

plot(NA, xlim=c(minx,maxx), ylim=c(miny,maxy), xlab="dim1", ylab="dim2")
ss <- 1
inn <- seq(1,length(files))
for( i in seq(1,length(files)) ){
	cat(files[i]," ", counts[i],"   ",colors[i]," ", ss,":",(ss+counts[i]-1),"\n")
	points(mds[ss:(ss+counts[i]-1),1], mds[ss:(ss+counts[i]-1),2], pch=19, cex=0.8, col=colors[i])
	# centroid
	points(mean(mds[ss:(ss+counts[i]-1),1]), mean(mds[ss:(ss+counts[i]-1),2]), pch=3, cex=0.8)
	ss <- ss + counts[i]
}
legend("topleft", files, col=legends, pch=19)

###########################
# 3D PLOT

mds3 <- cmdscale(corrMat, k=3 )
plot3d(NA)
ss <- 1
for( i in seq(1,length(files)) ){
	cat(files[i]," ", counts[i],"   ",colors[i]," ", ss,":",(ss+counts[i]-1),"\n")
	rgl.points(mds3[ss:(ss+counts[i]-1),1], mds3[ss:(ss+counts[i]-1),2], pch=24,cex=0.5, col=colors[i])
	ss <- ss + counts[i]
}


process.beast.files <- function(files, burnins, cols){

	counts <- c()
	dset = c()
	for( i in seq(1:length(files)) ){
		skippy <- 2 + burnins[i]
		cat("File: ", files[i], " skip:", skippy," ")
		#data <- read.csv(files[i], head=TRUE, sep="\t", skip=2 )
		#data <- data[burnins[i]:nrow(data),start:last]
		data <- read.csv(files[i], head=FALSE, sep="\t", skip=skippy )
		dset <- rbind(dset, data[,cols])
		counts <- c(counts, nrow(data))
		cat("nrow ", nrow(data), " ncol ", length(cols), "\n")
	}
	list(data=dset, counts=counts)
}
